---
title: "R Notebook"
output: html_notebook
---

```{python}
import pandas as pd
from pyprojroot import here
```

```{python}
# read in health board mortality data
hb_mortality = pd.read_csv(here('raw_data/stroke_mortalitybyhbr.csv'))

# read in council area mortality data
ca_mortality = pd.read_csv(here('raw_data/stroke_mortalitybyca.csv'))
```

```{r}
library(reticulate)
library(tidyverse)
# clean data using janitor
hb_mortality <- py$hb_mortality %>% 
  janitor::clean_names()

ca_mortality <- py$ca_mortality %>% 
  janitor::clean_names()
```


```{python}
# remove unnecessary columns
hb_mortality_reduced = r.hb_mortality.drop(columns = ['hbrqf', 'age_group_qf', 'sex_qf', 'number_of_deaths_qf', 'crude_rate_qf'])

ca_mortality_reduced = r.ca_mortality.drop(columns = ['caqf', 'age_group_qf', 'sex_qf', 'number_of_deaths_qf', 'crude_rate_qf'])
```

```{python}
# check sum of NAs
hb_refined.isna().sum()

ca_refined.isna().sum()
# NAs in number of deaths and crude rate
```



```{python}
# filter out Cerebrovascular and Stroke and keep "All" patients "All" sexes
hb_refined = hb_mortality_reduced.query('age_group == "All" & sex == "All"')

ca_refined = ca_mortality_reduced.query('age_group == "All" & sex == "All"')
```


```{python}
# group by year and diagnosis then sum number of deaths for each
grouped_deaths_hb = hb_refined.groupby(['year', 'diagnosis'])['number_of_deaths'].sum().reset_index()

grouped_deaths_ca = ca_refined.groupby(['year', 'diagnosis'])['number_of_deaths'].sum().reset_index()
```

```{python}
# pivot long the grouped data
deaths_pivoted = grouped_deaths_hb \
    .pivot(
        index='year', 
        columns='diagnosis', 
        values='number_of_deaths'
    ).reset_index()

deaths_pivoted
```

# Are there differences in mortality rates for different types of stroke?

```{python}
import matplotlib
import matplotlib.pyplot as plt
import numpy as np

plt.close()
plt.style.use('ggplot')

plt.plot(deaths_pivoted['year'], deaths_pivoted['Cerebrovascular Disease'], color='b', label='Cerebrovascular Disease')

plt.plot(deaths_pivoted['year'], deaths_pivoted['Stroke'], color='r', label='Stroke')

plt.plot(deaths_pivoted['year'], deaths_pivoted['Subarachnoid Haemorrhage'], color='y', label='Subarachnoid Haemorrhage')

plt.xticks(rotation = 30)
plt.legend(loc=1)
plt.title('Total Deaths by Stroke Type')
plt.ylabel('Number of Deaths')
plt.show()
```

```{python}
# filter for male and female, as well as all ages
hb_demo_refined = hb_mortality_reduced.query('sex != "All" & age_group == "All"')

ca_demo_refined = ca_mortality_reduced.query('sex != "All" & age_group == "All"')
```

```{python}
# group by diagnosis and gender then sum deaths by gender across health boards
demo_deaths_df = hb_demo_refined.groupby(['diagnosis', 'sex'])['number_of_deaths'].sum().reset_index()

# group by diagnosis and gender then sum deaths by gender across council areas
ca_demo_deaths_df = ca_demo_refined.groupby(['diagnosis', 'sex'])['number_of_deaths'].sum().reset_index()
```

```{python}
# pivot long the grouped data
deaths_by_gender_pivoted = demo_deaths_df \
    .pivot(
        index='diagnosis', 
        columns='sex', 
        values='number_of_deaths'
    ).reset_index()

deaths_by_gender_pivoted
```

# Does this vary with demographics?

```{python}

plt.close()
plt.style.use('ggplot')

x = ['Cerebrovascular Disease', 'Stroke', 'Subarachnoid Haemorrhage']
y_sub = [49808, 27912, 2300]
z_sub= [33340, 17512, 1120]

X_axis = np.arange(len(x))
  
plt.bar(X_axis - 0.2, y_sub, 0.4, label = 'Female')
plt.bar(X_axis + 0.2, z_sub, 0.4, label = 'Male')
  
plt.xticks(X_axis, x)
plt.xlabel("Diagnosis")
plt.ylabel("Number of Deaths")
plt.title("Number of Deaths by Diagnosis Type and Gender")
plt.legend()
plt.show()
```


```{python}
# filter for all ages
ca_age_mortality = ca_mortality_reduced.query('age_group != "All" & sex == "All"')

hb_age_mortality = hb_mortality_reduced.query('age_group != "All" & sex == "All"')
```

```{python}
ca_age_deaths_df = ca_age_mortality.groupby(['age_group', 'year', 'diagnosis'])['easr'].mean().reset_index()

hb_age_deaths_df = hb_age_mortality.groupby(['age_group', 'year', 'diagnosis'])['easr'].mean().reset_index()
```

```{python}
ca_deaths_by_age_pivoted = ca_age_deaths_df \
    .pivot(
        index=['age_group', 'year'], 
        columns='diagnosis', 
        values='easr'
    ).reset_index()

ca_deaths_by_age_pivoted
```

```{python}
plt.close()
plt.style.use('ggplot')

plt.plot(ca_deaths_by_age_pivoted['year'], ca_deaths_by_age_pivoted['Cerebrovascular Disease'], color='b', label='cer')

plt.plot(ca_deaths_by_age_pivoted['year'], ca_deaths_by_age_pivoted['Stroke'], color='r', label='Council Area')

plt.plot(ca_deaths_by_age_pivoted['year'], ca_deaths_by_age_pivoted['Subarachnoid Haemorrhage'], color='r', label='Council Area')

plt.xticks(rotation = 30)
plt.legend()
plt.title('Mean Crude Rate in Health Board vs Council Area')
plt.ylabel('Mean Crude Rate')
plt.show()
```

```{r}
py$ca_age_deaths_df %>%
  group_by(age_group, year) %>% 
  ggplot() +
  aes(x = year, y = easr, colour = age_group, group = age_group) +
  geom_point()+
  geom_line()+
  ggtitle("Subarachnoid Haemorrhage Mean Crude Rate by Age Group") +
  labs(x = "Financial Year",
       y = "Mean Crude Rate",
       colour = "Age Group") +
  theme_minimal()
```

